name: main
on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          python-version: '3.12'
          channels: bioconda,conda-forge
          channel-priority: true
          miniforge-version: "latest"
          activate-environment: snakemake

      - name: TMP
        run: |
            echo $CONDA_PREFIX
            echo $PATH

      - name: Snakemake
        run: |
          conda install -y -c bioconda -c conda-forge 'snakemake>=8.18.2,<9' 'python=3.12'
          snakemake --cores=1 --sdm=conda --conda-cleanup-pkgs=cache

