name: main
on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Snakemake
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores=1 --sdm=conda --conda-cleanup-pkgs=cache'
