name: main
on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          miniforge-version: "latest"
          conda-solver: "libmamba"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Snakemake
        run: |
          conda install -y -c bioconda snakemake
          snakemake --cores=1 --sdm=conda --conda-cleanup-pkgs=cache
